name: Version Bump Test

permissions:
  contents: write

on:
  push:
    branches:
      - test1

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Python version
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'

      - name: Install semantic-release
        run: |
          pip install python-semantic-release

      - name: Dry Run - Version Bump for Main Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd feluda
          semantic-release version --dry-run

      - name: Dry Run - Version Bump for Operator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd operators/image_vec_rep_resnet
          semantic-release version --dry-run